site_name: Foreman Infrastructure

nav:
  - Overview: index.md
  - Roles:
    - Discourse: discourse.md
    - Foreman: foreman.md
    - Jenkins: jenkins.md
    - Koji: koji.md
    - Puppet: puppet.md
    - Redmine: redmine.md
    - Virt: virt.md
    - Webserver: webserver.md
  - GPG: gpg.md
  - Secrets: secrets.md
  - Bootstrap: bootstrap.md
