site_name: Foreman Infrastructure

nav:
  - Overview: index.md
  - Roles:
    - Discourse: discourse.md
    - Foreman: foreman-puppetserver.md
    - Jenkins: jenkins.md
    - Koji: koji.md
    - Redmine: redmine.md
    - Virt: virt.md
    - Webserver: webserver.md
  - GPG: gpg.md
